# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: "Demo_DotNet_Project_Pool"
  demands:
    - agent.name -equals agent1

variables:
  buildconfiguration: "Release"
stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Restore & Build"
    steps:
    - task: DotNetCoreCLI@2
      displayName: "Restore Nuget Packages"
      inputs:
        command: "restore"
    
    - task: DotNetCoreCLI@2
      displayName: "Build the project"
      inputs:
        command: "build"
        projects: "**/*.csproj"
        arguments: "--configuration $(buildConfiguration)"
      
- stage: Publish
  displayName: "Publish Stage"
  jobs:
  - job: PublishJob
    displayName: "Publish the project"
    steps:
    - task: DotNetCoreCLI@2
      displayName: "Publish the project"
      inputs:
        command: "publish"
        projects: "**/*.csproj"
        arguments: "--configuration $(buildConfiguration) --output C:/customstagingdirectory"
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: 'c:/publishedfiles'
        ArtifactName: 'drop'
